
import { Question, QuestionType } from '../../../types';

export const READING_QUESTIONS: Record<string, Question[]> = {
  'r-p1-underground': [
    { id: 1, type: QuestionType.TFNG, text: "Carbon sequestration is a new concept that has never been used before.", correctAnswer: "FALSE" },
    { id: 2, type: QuestionType.TFNG, text: "The world's largest carbon sequestration experiment is taking place in Iceland.", correctAnswer: "TRUE" },
    { id: 3, type: QuestionType.TFNG, text: "Carbon sequestration could be a solution to global warming.", correctAnswer: "TRUE" },
    { id: 4, type: QuestionType.TFNG, text: "The technology for carbon sequestration is already fully developed and ready for use.", correctAnswer: "FALSE" },
    { id: 5, type: QuestionType.FILL_GAPS, text: "Carbon sequestration involves capturing emissions from power plants and factories and forcing them .................", correctAnswer: "underground", placeholder: "5." },
    { id: 6, type: QuestionType.MATCHING_ENDINGS, text: "The main purpose of carbon sequestration is to", options: [{ label: "A - reduce greenhouse gas emissions", value: "A" }, { label: "B - improve oil well efficiency", value: "B" }, { label: "C - reduce the cost of energy production", value: "C" }, { label: "D - generate new sources of income", value: "D" }], correctAnswer: "A" },
    { id: 7, type: QuestionType.FILL_GAPS, text: "There are two main methods of capturing carbon dioxide: post-combustion capture and ................. capture.", correctAnswer: "pre-combustion", placeholder: "7." },
    { id: 8, type: QuestionType.MATCHING_ENDINGS, text: "Suitable rock formations for storing carbon dioxide include", options: [{ label: "A - only depleted oil and gas reservoirs", value: "A" }, { label: "B - only unmineable coal seams", value: "B" }, { label: "C - only saline aquifers", value: "C" }, { label: "D - all of the above", value: "D" }], correctAnswer: "D" },
    { id: 9, type: QuestionType.TFNG, text: "Carbon dioxide stored underground could potentially escape and become lethal.", correctAnswer: "TRUE" },
    { id: 10, type: QuestionType.TFNG, text: "Artificial storage of carbon dioxide would not be monitored at all.", correctAnswer: "FALSE" },
    { id: 11, type: QuestionType.FILL_GAPS, text: "Scientists estimate that properly stored carbon dioxide could remain underground for ................. of years.", correctAnswer: "thousands", placeholder: "11." },
    { id: 12, type: QuestionType.TFNG, text: "Carbon sequestration is a complete solution to the climate problem on its own.", correctAnswer: "FALSE" },
    { id: 13, type: QuestionType.MATCHING_ENDINGS, text: "Capturing carbon dioxide from a power plant can reduce the plant's output by up to", options: [{ label: "A - 10 percent", value: "A" }, { label: "B - 20 percent", value: "B" }, { label: "C - 30 percent", value: "C" }, { label: "D - 40 percent", value: "D" }], correctAnswer: "C" }
  ],
  'r-p1': [
    { id: 1, type: QuestionType.CLASSIFICATION, text: "being expensive", correctAnswer: "C", options: [{label: "ambergris only", value: "A"}, {label: "amber only", value: "B"}, {label: "both ambergris and amber", value: "C"}, {label: "neither ambergris nor amber", value: "D"}] },
    { id: 2, type: QuestionType.CLASSIFICATION, text: "adds flavor to food", correctAnswer: "A", options: [{label: "ambergris only", value: "A"}, {label: "amber only", value: "B"}, {label: "both ambergris and amber", value: "C"}, {label: "neither ambergris nor amber", value: "D"}] },
    { id: 3, type: QuestionType.CLASSIFICATION, text: "used as currency", correctAnswer: "D", options: [{label: "ambergris only", value: "A"}, {label: "amber only", value: "B"}, {label: "both ambergris and amber", value: "C"}, {label: "neither ambergris nor amber", value: "D"}] },
    { id: 4, type: QuestionType.CLASSIFICATION, text: "being see-through", correctAnswer: "B", options: [{label: "ambergris only", value: "A"}, {label: "amber only", value: "B"}, {label: "both ambergris and amber", value: "C"}, {label: "neither ambergris nor amber", value: "D"}] },
    { id: 5, type: QuestionType.CLASSIFICATION, text: "referred to by Herman Melville", correctAnswer: "A", options: [{label: "ambergris only", value: "A"}, {label: "amber only", value: "B"}, {label: "both ambergris and amber", value: "C"}, {label: "neither ambergris nor amber", value: "D"}] },
    { id: 6, type: QuestionType.CLASSIFICATION, text: "produces sweet smell", correctAnswer: "A", options: [{label: "ambergris only", value: "A"}, {label: "amber only", value: "B"}, {label: "both ambergris and amber", value: "C"}, {label: "neither ambergris nor amber", value: "D"}] },
    { id: 7, type: QuestionType.FILL_GAPS, text: "Sperm whales can't digest the ................. of the squids.", correctAnswer: "beaks", placeholder: "7." },
    { id: 8, type: QuestionType.FILL_GAPS, text: "Sperm whales drive the irritants out of their intestines by .................", correctAnswer: "vomiting", placeholder: "8." },
    { id: 9, type: QuestionType.FILL_GAPS, text: "The vomit of sperm whales gradually ................. on contact of air before having pleasant smell.", correctAnswer: "hardens", placeholder: "9." },
    { id: 10, type: QuestionType.TFNG, text: "Most ambergris comes from the dead whales today.", correctAnswer: "TRUE" },
    { id: 11, type: QuestionType.TFNG, text: "Ambergris is becoming more expensive than before.", correctAnswer: "NOT GIVEN" },
    { id: 12, type: QuestionType.TFNG, text: "Ambergris is still a popular ingredient in perfume production today.", correctAnswer: "FALSE" },
    { id: 13, type: QuestionType.TFNG, text: "New uses of ambergris have been discovered recently.", correctAnswer: "NOT GIVEN" }
  ],
  'r-cultural-tourist': [
    { id: 1, type: QuestionType.TFNG, text: "Cyriacus was unable to research his journeys before he left.", correctAnswer: "TRUE" },
    { id: 2, type: QuestionType.TFNG, text: "The Roman Emperor Trajan built the city of Ancona", correctAnswer: "NOT GIVEN" },
    { id: 3, type: QuestionType.TFNG, text: "Respect for ancient architecture was widespread in the 15th century", correctAnswer: "FALSE" },
    { id: 4, type: QuestionType.TFNG, text: "Cyriacus’s experience as a merchant gave him skills he needed to investigate the ancient world.", correctAnswer: "FALSE" },
    { id: 5, type: QuestionType.TFNG, text: "Before leaving on his journey, Cyriacus studied ancient languages.", correctAnswer: "TRUE" },
    { id: 6, type: QuestionType.TFNG, text: "Travelling by sea in the 15th century was easier than travelling on land.", correctAnswer: "FALSE" },
    { id: 7, type: QuestionType.TFNG, text: "Cyriacus tried to make his fellow sea travelers more comfortable", correctAnswer: "NOT GIVEN" },
    { id: 8, type: QuestionType.FILL_GAPS, text: "the wealth of the city had come from", correctAnswer: "commerce", placeholder: "8." },
    { id: 9, type: QuestionType.FILL_GAPS, text: "to the ancient city ruins not available when visited by Cyriacus", correctAnswer: "guidebook", placeholder: "9." },
    { id: 10, type: QuestionType.FILL_GAPS, text: "the city was destroyed by a powerful", correctAnswer: "earthquake", placeholder: "10." },
    { id: 11, type: QuestionType.FILL_GAPS, text: "a year later Emperor Hadrian supported a", correctAnswer: "campaign", placeholder: "11." },
    { id: 12, type: QuestionType.FILL_GAPS, text: "Cyriacus found part of the temple... and made drawings of the", correctAnswer: "doorway", placeholder: "12." },
    { id: 13, type: QuestionType.FILL_GAPS, text: "by the 15th century Delphi had almost disappeared due to natural disasters and", correctAnswer: "war", placeholder: "13." }
  ],
  'r-p3': [
    { id: 27, type: QuestionType.MATCHING_ENDINGS, text: "The speed of technological changes", options: [{ label: "A - requires more detailed study by psychologists", value: "A" }, { label: "B - means people have no time to challenge the significance of the new technology", value: "B" }, { label: "C - may reduce inventiveness and innovation", value: "C" }, { label: "D - suggests computers will take over the workplace", value: "D" }, { label: "E - results from increased electronic supervision", value: "E" }], correctAnswer: "B" },
    { id: 28, type: QuestionType.MATCHING_ENDINGS, text: "A dependency on technology and computers", options: [{ label: "A - requires more detailed study by psychologists", value: "A" }, { label: "B - means people have no time to challenge the significance of the new technology", value: "B" }, { label: "C - may reduce inventiveness and innovation", value: "C" }, { label: "D - suggests computers will take over the workplace", value: "D" }, { label: "E - results from increased electronic supervision", value: "E" }], correctAnswer: "C" },
    { id: 29, type: QuestionType.MATCHING_ENDINGS, text: "A deterioration in personal service", options: [{ label: "A - requires more detailed study by psychologists", value: "A" }, { label: "B - means people have no time to challenge the significance of the new technology", value: "B" }, { label: "C - may reduce inventiveness and innovation", value: "C" }, { label: "D - suggests computers will take over the workplace", value: "D" }, { label: "E - results from increased electronic supervision", value: "E" }], correctAnswer: "E" },
    { id: 30, type: QuestionType.MATCHING_PEOPLE, text: "Technology has placed greater expectations on workers not to make mistakes.", options: [{ label: "A - Craig Brod", value: "A" }, { label: "B - Daniel Dennett", value: "B" }, { label: "C - Joseph Boyett and Henry Conn", value: "C" }, { label: "D - Philip Nicholson", value: "D" }], correctAnswer: "B" },
    { id: 31, type: QuestionType.MATCHING_PEOPLE, text: "People will need time away from technology to reduce the frustrations caused by it.", options: [{ label: "A - Craig Brod", value: "A" }, { label: "B - Daniel Dennett", value: "B" }, { label: "C - Joseph Boyett and Henry Conn", value: "C" }, { label: "D - Philip Nicholson", value: "D" }], correctAnswer: "A" },
    { id: 32, type: QuestionType.MATCHING_PEOPLE, text: "Interacting with others at work contributes to creative thinking.", options: [{ label: "A - Craig Brod", value: "A" }, { label: "B - Daniel Dennett", value: "B" }, { label: "C - Joseph Boyett and Henry Conn", value: "C" }, { label: "D - Philip Nicholson", value: "D" }], correctAnswer: "A" },
    { id: 33, type: QuestionType.MATCHING_PEOPLE, text: "The psychological effect of working with technology is similar to the anxiety felt after surviving a major ordeal.", options: [{ label: "A - Craig Brod", value: "A" }, { label: "B - Daniel Dennett", value: "B" }, { label: "C - Joseph Boyett and Henry Conn", value: "C" }, { label: "D - Philip Nicholson", value: "D" }], correctAnswer: "D" },
    { id: 34, type: QuestionType.MATCHING_PEOPLE, text: "Technology will ultimately increase unemployment for more highly qualified personnel.", options: [{ label: "A - Craig Brod", value: "A" }, { label: "B - Daniel Dennett", value: "B" }, { label: "C - Joseph Boyett and Henry Conn", value: "C" }, { label: "D - Philip Nicholson", value: "D" }], correctAnswer: "C" },
    { id: 35, type: QuestionType.MATCHING_PEOPLE, text: "More counselling is required to help people cope with the demands of the modern workplace.", options: [{ label: "A - Craig Brod", value: "A" }, { label: "B - Daniel Dennett", value: "B" }, { label: "C - Joseph Boyett and Henry Conn", value: "C" }, { label: "D - Philip Nicholson", value: "D" }], correctAnswer: "D" },
    { id: 36, type: QuestionType.TFNG, text: "Our knowledge of the effects of technology on workers is still limited.", options: [{ label: "TRUE", value: "TRUE" }, { label: "FALSE", value: "FALSE" }, { label: "NOT GIVEN", value: "NOT GIVEN" }], correctAnswer: "TRUE" },
    { id: 37, type: QuestionType.TFNG, text: "An early indicator of technological anxiety is a tendency to adopt machine-like thinking.", options: [{ label: "TRUE", value: "TRUE" }, { label: "FALSE", value: "FALSE" }, { label: "NOT GIVEN", value: "NOT GIVEN" }], correctAnswer: "TRUE" },
    { id: 38, type: QuestionType.TFNG, text: "We have now started to doubt our ability to perform well at work.", options: [{ label: "TRUE", value: "TRUE" }, { label: "FALSE", value: "FALSE" }, { label: "NOT GIVEN", value: "NOT GIVEN" }], correctAnswer: "TRUE" },
    { id: 39, type: QuestionType.TFNG, text: "Top level managers may be more negatively affected by changes electronic workplace than junior workers.", options: [{ label: "TRUE", value: "TRUE" }, { label: "FALSE", value: "FALSE" }, { label: "NOT GIVEN", value: "NOT GIVEN" }], correctAnswer: "NOT GIVEN" },
    { id: 40, type: QuestionType.TFNG, text: "Employees who learn to use new technology quickly will get promoted.", options: [{ label: "TRUE", value: "TRUE" }, { label: "FALSE", value: "FALSE" }, { label: "NOT GIVEN", value: "NOT GIVEN" }], correctAnswer: "NOT GIVEN" }
  ],
  'r-ascension': [
    { id: 1, type: QuestionType.TFNG, text: "People can visit Ascension easily today.", correctAnswer: "FALSE" },
    { id: 2, type: QuestionType.TFNG, text: "The mid-Atlantic ridge continues to experience volcanic activity.", correctAnswer: "TRUE" },
    { id: 3, type: QuestionType.TFNG, text: "João da Nova Castella was the first to call his discovery Ascension Island.", correctAnswer: "FALSE" },
    { id: 4, type: QuestionType.TFNG, text: "When the island was discovered, its center contained more life than the area near the sea.", correctAnswer: "NOT GIVEN" },
    { id: 5, type: QuestionType.TFNG, text: "The Portuguese military wanted to use the island as a base.", correctAnswer: "NOT GIVEN" },
    { id: 6, type: QuestionType.TFNG, text: "In the 19th century, Ascension Island acted as an important port for naval supplies.", correctAnswer: "TRUE" },
    { id: 7, type: QuestionType.TFNG, text: "The British imported fresh water to Ascension Island from southern Africa.", correctAnswer: "FALSE" },
    { id: 8, type: QuestionType.TFNG, text: "When it rained on Ascension Island, the water quickly dried up.", correctAnswer: "TRUE" },
    { id: 9, type: QuestionType.FILL_GAPS, text: "before his 1836 visit, Darwin had limited ............. of what he might find", correctAnswer: "expectations", placeholder: "9." },
    { id: 10, type: QuestionType.FILL_GAPS, text: "after his arrival, Darwin saw the ............. of the island and so devised a plan", correctAnswer: "potential", placeholder: "10." },
    { id: 11, type: QuestionType.FILL_GAPS, text: "on an expedition to explore the area around ............. , Hooker visited Ascension", correctAnswer: "Antarctica", placeholder: "11." },
    { id: 12, type: QuestionType.FILL_GAPS, text: "trees were planted on Ascension to lessen the ............. of rainwater", correctAnswer: "evaporation", placeholder: "12." },
    { id: 13, type: QuestionType.FILL_GAPS, text: "from the 1850s, plants were brought to Ascension from ............. around the world", correctAnswer: "gardens", placeholder: "13." },
    { id: 14, type: QuestionType.FILL_GAPS, text: "the cloud forest traps moisture contained in the ............. which blows off the ocean", correctAnswer: "mist", placeholder: "14." },
    { id: 15, type: QuestionType.FILL_GAPS, text: "the cloud forest is a successful man-made .............", correctAnswer: "ecosystem", placeholder: "15." },
    { id: 16, type: QuestionType.FILL_GAPS, text: "According to Dr Dave Wilkinson, the ideas learned from Ascension may be applicable to life in future human ............. on Mars.", correctAnswer: "colonies", placeholder: "16." }
  ],
  'r-beatrix-potter': [
    { id: 1, type: QuestionType.TFNG, text: "The Tale of Peter Rabbit was Beatrix Potter's first published book.", correctAnswer: "FALSE" },
    { id: 2, type: QuestionType.TFNG, text: "Beatrix Potter was educated at a traditional school.", correctAnswer: "FALSE" },
    { id: 3, type: QuestionType.TFNG, text: "Beatrix Potter kept a diary in a secret code as a teenager.", correctAnswer: "TRUE" },
    { id: 4, type: QuestionType.TFNG, text: "Beatrix Potter received formal art training at a prestigious academy.", correctAnswer: "FALSE" },
    { id: 5, type: QuestionType.TFNG, text: "Beatrix Potter was interested in studying fungi scientifically.", correctAnswer: "TRUE" },
    { id: 6, type: QuestionType.TFNG, text: "Beatrix Potter married early in her twenties.", correctAnswer: "FALSE" },
    { id: 7, type: QuestionType.TFNG, text: "The Tale of Peter Rabbit was initially rejected by publishers.", correctAnswer: "TRUE" },
    { id: 8, type: QuestionType.TFNG, text: "Norman Warne was the oldest brother in the publishing company.", correctAnswer: "FALSE" },
    { id: 9, type: QuestionType.FILL_GAPS, text: "Beatrix Potter was born in London in .............", correctAnswer: "1866", placeholder: "9." },
    { id: 10, type: QuestionType.FILL_GAPS, text: "As a child, Beatrix Potter kept many animals including rabbits, frogs and .............", correctAnswer: "bats", placeholder: "10." },
    { id: 11, type: QuestionType.FILL_GAPS, text: "Beatrix Potter wanted to study at ............. in London but was rejected because of her gender.", correctAnswer: "Kew", placeholder: "11." },
    { id: 12, type: QuestionType.FILL_GAPS, text: "Beatrix Potter remained ............. throughout her life.", correctAnswer: "single", placeholder: "12." },
    { id: 13, type: QuestionType.FILL_GAPS, text: "Beatrix Potter moved to the ............. in northern England after Warne's death.", correctAnswer: "Lake District", placeholder: "13." },
    { id: 14, type: QuestionType.FILL_GAPS, text: "Beatrix Potter left over 4,000 acres of land to the .............", correctAnswer: "National Trust", placeholder: "14." }
  ],
  'r-bondi': [
    { id: 1, type: QuestionType.TFNG, text: "Australians have always valued Bondi Beach as a national treasure.", correctAnswer: "FALSE" },
    { id: 2, type: QuestionType.TFNG, text: "Aboriginal people had a strong connection to the Australian coast before British settlement.", correctAnswer: "TRUE" },
    { id: 3, type: QuestionType.TFNG, text: "The cultural associations of Australia's beaches are entirely indigenous in origin.", correctAnswer: "FALSE" },
    { id: 4, type: QuestionType.TFNG, text: "Brighton Beach in England influenced the development of Australian beach culture.", correctAnswer: "TRUE" },
    { id: 5, type: QuestionType.TFNG, text: "Coogee was the first Sydney beach to be accessible by tram.", correctAnswer: "TRUE" },
    { id: 6, type: QuestionType.TFNG, text: "Manly Beach attracted primarily working-class visitors.", correctAnswer: "FALSE" },
    { id: 7, type: QuestionType.TFNG, text: "Bondi developed differently from other Sydney beach suburbs because of flat construction.", correctAnswer: "TRUE" },
    { id: 8, type: QuestionType.TFNG, text: "Bondi's working-class character changed in the 1950s after the royal visit.", correctAnswer: "TRUE" },
    { id: 9, type: QuestionType.FILL_GAPS, text: "In the first century of British settlement, Australians were fascinated by the ............. interior.", correctAnswer: "desert", placeholder: "9." },
    { id: 10, type: QuestionType.FILL_GAPS, text: "By the 1820s, the local Aboriginal population near Sydney had largely disappeared due to .............", correctAnswer: "diseases", placeholder: "10." },
    { id: 11, type: QuestionType.FILL_GAPS, text: "At the end of the 19th century, the beach emerged as an alternative cultural ............. to the mythology of the interior.", correctAnswer: "landscape", placeholder: "11." },
    { id: 12, type: QuestionType.FILL_GAPS, text: "The 1954 royal visit brought ............. attention to Bondi Beach.", correctAnswer: "international", placeholder: "12." },
    { id: 13, type: QuestionType.FILL_GAPS, text: "Since the 1970s, Bondi has become the ............. backdrop for any artistic project requiring a beach setting.", correctAnswer: "inevitable", placeholder: "13." },
    { id: 14, type: QuestionType.FILL_GAPS, text: "For the 2000 Olympics, Bondi was chosen to host the beach ............. stadium.", correctAnswer: "volleyball", placeholder: "14." }
  ],
  'r-triumph-city': [
    { id: 1, type: QuestionType.TFNG, text: "Edward Glaeser argues that cities are unhealthy places that should be avoided.", correctAnswer: "FALSE" },
    { id: 2, type: QuestionType.TFNG, text: "Glaeser believes that proximity to intelligent people enhances our own intelligence.", correctAnswer: "TRUE" },
    { id: 3, type: QuestionType.TFNG, text: "Denser cities tend to have lower incomes per capita according to Glaeser's data.", correctAnswer: "FALSE" },
    { id: 4, type: QuestionType.TFNG, text: "Glaeser claims that city residents have a smaller carbon footprint than suburban residents.", correctAnswer: "TRUE" },
    { id: 5, type: QuestionType.TFNG, text: "The author supports strict zoning laws to control urban growth.", correctAnswer: "FALSE" },
    { id: 6, type: QuestionType.TFNG, text: "Critics argue that Glaeser's analysis ignores the problems of urban poverty.", correctAnswer: "TRUE" },
    { id: 7, type: QuestionType.TFNG, text: "Glaeser believes that preserving rural landscapes is more important than urban development.", correctAnswer: "FALSE" },
    { id: 8, type: QuestionType.TFNG, text: "More than half of the global population now lives in cities.", correctAnswer: "TRUE" },
    { id: 9, type: QuestionType.FILL_GAPS, text: "Glaeser's book is titled '............. of the City'.", correctAnswer: "Triumph", placeholder: "9." },
    { id: 10, type: QuestionType.FILL_GAPS, text: "Glaeser works as an economist at ............. University.", correctAnswer: "Harvard", placeholder: "10." },
    { id: 11, type: QuestionType.FILL_GAPS, text: "The author uses the term 'human capital .............' to describe the benefits of city living.", correctAnswer: "spillovers", placeholder: "11." },
    { id: 12, type: QuestionType.FILL_GAPS, text: "Glaeser argues that cities enable innovation through the ............. of people.", correctAnswer: "connection", placeholder: "12." },
    { id: 13, type: QuestionType.FILL_GAPS, text: "The book critiques urban planning policies like ............. laws that restrict housing supply.", correctAnswer: "zoning", placeholder: "13." },
    { id: 14, type: QuestionType.FILL_GAPS, text: "According to the review, the triumph of the city represents the triumph of human .............", correctAnswer: "connection", placeholder: "14." }
  ],
  // PASSAGE 2 QUESTIONS
  'r-p2-computer-games': [
    { id: 1, type: QuestionType.TFNG, text: "Computer games are only popular among young people.", correctAnswer: "FALSE" },
    { id: 2, type: QuestionType.TFNG, text: "Action games have been linked to enhanced attention and faster reaction times.", correctAnswer: "TRUE" },
    { id: 3, type: QuestionType.TFNG, text: "The concept of educational games is a recent development.", correctAnswer: "TRUE" },
    { id: 4, type: QuestionType.TFNG, text: "Research shows that all types of computer games improve cognitive abilities.", correctAnswer: "FALSE" },
    { id: 5, type: QuestionType.TFNG, text: "Excessive gaming has been linked to attention problems and obesity.", correctAnswer: "TRUE" },
    { id: 6, type: QuestionType.TFNG, text: "All researchers agree that violent video games cause aggressive behaviour.", correctAnswer: "FALSE" },
    { id: 7, type: QuestionType.TFNG, text: "The gaming industry has introduced features to promote healthy gaming habits.", correctAnswer: "TRUE" },
    { id: 8, type: QuestionType.TFNG, text: "Virtual reality is currently only used for entertainment purposes.", correctAnswer: "FALSE" },
    { id: 9, type: QuestionType.FILL_GAPS, text: "Computer games have become one of the most popular forms of ............. in the modern world.", correctAnswer: "entertainment", placeholder: "9." },
    { id: 10, type: QuestionType.FILL_GAPS, text: "The concept of '.............' combines education with entertainment.", correctAnswer: "edutainment", placeholder: "10." },
    { id: 11, type: QuestionType.FILL_GAPS, text: "Some researchers have found links between violent games and reduced ............. behaviour.", correctAnswer: "prosocial", placeholder: "11." },
    { id: 12, type: QuestionType.FILL_GAPS, text: "Many games now include systems that remind players to take .............", correctAnswer: "breaks", placeholder: "12." },
    { id: 13, type: QuestionType.FILL_GAPS, text: "The key challenge will be harnessing the power of technology while mitigating potential .............", correctAnswer: "harms", placeholder: "13." },
    { id: 14, type: QuestionType.FILL_GAPS, text: "Some people view games as a powerful medium with the potential to ............. people around the world.", correctAnswer: "connect", placeholder: "14." }
  ],
  'r-p2-chocolate': [
    { id: 1, type: QuestionType.TFNG, text: "Chocolate was first consumed by ancient European civilizations.", correctAnswer: "FALSE" },
    { id: 2, type: QuestionType.TFNG, text: "Cacao beans were used as currency by Mesoamerican civilizations.", correctAnswer: "TRUE" },
    { id: 3, type: QuestionType.TFNG, text: "The addition of sugar transformed chocolate into a sweet treat.", correctAnswer: "TRUE" },
    { id: 4, type: QuestionType.TFNG, text: "Milk chocolate was invented before sugar was added to chocolate.", correctAnswer: "FALSE" },
    { id: 5, type: QuestionType.TFNG, text: "The chocolate industry faces environmental challenges related to cacao production.", correctAnswer: "TRUE" },
    { id: 6, type: QuestionType.TFNG, text: "Fair trade certification guarantees that farmers receive a maximum price for cacao.", correctAnswer: "FALSE" },
    { id: 7, type: QuestionType.TFNG, text: "Consumer demand for dark chocolate with higher cacao content is growing.", correctAnswer: "TRUE" },
    { id: 8, type: QuestionType.TFNG, text: "Chocolate production has no significant impact on the global economy.", correctAnswer: "FALSE" },
    { id: 9, type: QuestionType.FILL_GAPS, text: "Chocolate is derived from the ............. plant native to Mesoamerica.", correctAnswer: "cacao", placeholder: "9." },
    { id: 10, type: QuestionType.FILL_GAPS, text: "The industrial revolution brought significant changes to chocolate .............", correctAnswer: "production", placeholder: "10." },
    { id: 11, type: QuestionType.FILL_GAPS, text: "Cacao farming has led to ............. in many producing regions.", correctAnswer: "deforestation", placeholder: "11." },
    { id: 12, type: QuestionType.FILL_GAPS, text: "............. certification guarantees farmers receive a minimum price for their cacao.", correctAnswer: "Fair trade", placeholder: "12." },
    { id: 13, type: QuestionType.FILL_GAPS, text: "There is growing demand for organic and ............. chocolates.", correctAnswer: "specialty", placeholder: "13." },
    { id: 14, type: QuestionType.FILL_GAPS, text: "The global chocolate industry is worth ............. of dollars.", correctAnswer: "billions", placeholder: "14." }
  ],
  // PASSAGE 3 QUESTIONS
  'r-p3-feeding-world': [
    { id: 1, type: QuestionType.TFNG, text: "The global population is projected to decrease by 2050.", correctAnswer: "FALSE" },
    { id: 2, type: QuestionType.TFNG, text: "Technological innovations can help increase agricultural productivity.", correctAnswer: "TRUE" },
    { id: 3, type: QuestionType.TFNG, text: "Smallholder farmers in developing countries have easy access to new technologies.", correctAnswer: "FALSE" },
    { id: 4, type: QuestionType.TFNG, text: "Approximately one-third of all food produced is lost or wasted.", correctAnswer: "TRUE" },
    { id: 5, type: QuestionType.TFNG, text: "Plant-based diets require more resources than meat-based diets.", correctAnswer: "FALSE" },
    { id: 6, type: QuestionType.TFNG, text: "Climate change is affecting crop yields in many regions.", correctAnswer: "TRUE" },
    { id: 7, type: QuestionType.TFNG, text: "Biofuel production has no impact on food production.", correctAnswer: "FALSE" },
    { id: 8, type: QuestionType.TFNG, text: "Addressing food security requires a combination of approaches.", correctAnswer: "TRUE" },
    { id: 9, type: QuestionType.FILL_GAPS, text: "The global population is projected to reach ............. billion by 2050.", correctAnswer: "9.7", placeholder: "9." },
    { id: 10, type: QuestionType.FILL_GAPS, text: "Genetically modified organisms are one approach to increase agricultural .............", correctAnswer: "productivity", placeholder: "10." },
    { id: 11, type: QuestionType.FILL_GAPS, text: "In developing countries, food losses often occur during ............. due to inadequate infrastructure.", correctAnswer: "storage", placeholder: "11." },
    { id: 12, type: QuestionType.FILL_GAPS, text: "Livestock production requires significantly more ............. and water than plant-based foods.", correctAnswer: "land", placeholder: "12." },
    { id: 13, type: QuestionType.FILL_GAPS, text: "Developing climate-............. crop varieties will be essential for food security.", correctAnswer: "resilient", placeholder: "13." },
    { id: 14, type: QuestionType.FILL_GAPS, text: "Integrated strategies must consider the environmental, social, and ............. dimensions of food production.", correctAnswer: "economic", placeholder: "14." }
  ],
  'r-p3-antarctica': [
    { id: 1, type: QuestionType.TFNG, text: "Antarctica is a tropical continent with mild temperatures.", correctAnswer: "FALSE" },
    { id: 2, type: QuestionType.TFNG, text: "The Heroic Age of Antarctic Exploration occurred in the late 19th and early 20th centuries.", correctAnswer: "TRUE" },
    { id: 3, type: QuestionType.TFNG, text: "Roald Amundsen was the first person to reach the South Pole.", correctAnswer: "TRUE" },
    { id: 4, type: QuestionType.TFNG, text: "Robert Falcon Scott survived his expedition to the South Pole.", correctAnswer: "FALSE" },
    { id: 5, type: QuestionType.TFNG, text: "The Antarctic Treaty was signed in the 19th century.", correctAnswer: "FALSE" },
    { id: 6, type: QuestionType.TFNG, text: "Today, over 70 research stations operate in Antarctica.", correctAnswer: "TRUE" },
    { id: 7, type: QuestionType.TFNG, text: "Antarctic ice sheets contain a record of Earth's climate history.", correctAnswer: "TRUE" },
    { id: 8, type: QuestionType.TFNG, text: "Working in Antarctica is easy and inexpensive.", correctAnswer: "FALSE" },
    { id: 9, type: QuestionType.FILL_GAPS, text: "Antarctica covers nearly ............. million square kilometres.", correctAnswer: "14", placeholder: "9." },
    { id: 10, type: QuestionType.FILL_GAPS, text: "The Heroic Age of Antarctic Exploration lasted from roughly 1895 to .............", correctAnswer: "1922", placeholder: "10." },
    { id: 11, type: QuestionType.FILL_GAPS, text: "The International Geophysical Year of 1957-1958 sparked a surge in Antarctic .............", correctAnswer: "research", placeholder: "11." },
    { id: 12, type: QuestionType.FILL_GAPS, text: "The Antarctic ............. of 1959 set aside the continent for peaceful purposes.", correctAnswer: "Treaty", placeholder: "12." },
    { id: 13, type: QuestionType.FILL_GAPS, text: "The West Antarctic Ice Sheet contains enough water to raise global sea levels by several .............", correctAnswer: "metres", placeholder: "13." },
    { id: 14, type: QuestionType.FILL_GAPS, text: "Supplies must be shipped or flown in during the brief Antarctic .............", correctAnswer: "summer", placeholder: "14." }
  ]
};
